from __future__ import print_function
import json
import os

def list_gen_dir(type):
    path = os.path.join('src', 'gen', type)
    return [os.path.join(path, x) for x in os.listdir(path)]

def main():
    gen_files = {'djinni_gen_{}_files'.format(t): list_gen_dir(t)
                 for t in ['cpp', 'jni', 'objc', 'java']}
    with open('djinni_outputs.gypi', 'w') as outputs_file:
        print('# XXX AUTOGENERATED', file=outputs_file)
        json.dump({'variables': gen_files},
                  outputs_file, indent=4, separators=(',', ': '))

if __name__ == '__main__':
    main()
