from __future__ import print_function
import json
import os

def listdir_rel(path):
    return [os.path.join(path, x) for x in os.listdir(path)]

def main():
    gen_cpp_files = listdir_rel(os.path.join('src', 'gen', 'cpp'))
    gen_jni_files = listdir_rel(os.path.join('src', 'gen', 'jni'))
    gen_objc_files = listdir_rel(os.path.join('src', 'gen', 'objc'))
    gen_java_files = listdir_rel(os.path.join('src', 'gen', 'java'))
    with open('djinni_outputs.gypi', 'w') as outputs_file:
        print('# XXX AUTOGENERATED', file=outputs_file)
        json.dump({
            'variables': {
                'djinni_gen_cpp_files': gen_cpp_files,
                'djinni_gen_jni_files': gen_jni_files,
                'djinni_gen_objc_files': gen_objc_files,
                'djinni_gen_java_files': gen_java_files,
            }
        }, outputs_file, indent=4, separators=(',', ': '))

if __name__ == '__main__':
    main()
